#!/bin/sh
#* screensaverset
#+ chris.gerke@gmail.com
#+
#+ Description: Default Screensaver.
#+
#+ Version: 1.0
#+
#+ History:
#+     1.0: Script.
#+
#+ TODO:
#+     * Add error checking?

ME=$0
SCRIPT_DIR="$1/Contents/Resources"
TARGET_DIR="$3"

#+ // fix
if [ -z "${TARGET_DIR}" ] || [ "${TARGET_DIR}" = "/" ]; then
 TARGET_DIR=""
fi

#+ UUID
if [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` == "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c51-62 | awk {'print tolower()'}`
elif [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` != "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-62`
fi

#+ Apple User Template
for USER_TEMPLATE in `sudo /bin/ls "/System/Library/User Template"`
do
 if [ -r "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences" ]; then
  sudo /bin/mkdir -p "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost"
  #+ com.apple.screensaver.plist
  sudo /usr/bin/defaults write "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.screensaver" "askForPassword" -int "1"
  sudo /usr/bin/defaults write "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.screensaver" "askForPasswordDelay" -int "5"
  #+ com.apple.screensaver.${UUID}.plist
  sudo /usr/bin/defaults write "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}" "CleanExit" -string "YES"
  sudo /usr/libexec/PlistBuddy -c 'Add :CleanExit string YES' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :idleTime integer 900' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict dict' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:iLifeMediaGroupType integer 0' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:moduleName string Default" "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:path string ${TARGET_DIR}/Library/Screen Savers/Default.slideSaver" "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:type integer 4' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :DisplayType string Photos' "${TARGET_DIR}/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.screensaver.Default.${UUID}.plist"
 fi
done

#+ Existing users
for USER_DIR in `sudo /bin/ls "/Users"`
do
 if [ -r "${TARGET_DIR}/Users/Library/Preferences" ]; then
  sudo /bin/mkdir -p "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost"
  #+ com.apple.screensaver.plist
  sudo /usr/bin/defaults write "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/com.apple.screensaver" "askForPassword" -int "1"
  sudo /usr/bin/defaults write "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/com.apple.screensaver" "askForPasswordDelay" -int "5"
  #+ com.apple.screensaver.${UUID}.plist
  sudo /usr/bin/defaults write "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}" "CleanExit" -string "YES"
  sudo /usr/libexec/PlistBuddy -c 'Add :CleanExit string YES' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :idleTime integer 900' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict dict' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:iLifeMediaGroupType integer 0' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:moduleName string Default" "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:path string ${TARGET_DIR}/Library/Screen Savers/Default.slideSaver" "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:type integer 4' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add :DisplayType string Photos' "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.Default.${UUID}.plist"
  #+ Lockfile
  sudo /bin/rm -Rf "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/com.apple.screensaver.plist.lockfile"
  sudo /bin/rm -Rf "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist.lockfile"
  sudo /bin/rm -Rf "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.screensaver.Default.${UUID}.plist.lockfile"
  #+ Permissions
  sudo /usr/sbin/chown -R "${USER_DIR}" "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences"
 fi
done

#+ Unload Daemon
#sudo /bin/launchctl unload -w "/Library/LaunchDaemons/ScreenSaver.plist"
sudo /bin/rm -Rf "/Library/LaunchDaemons/ScreenSaver.plist"

exit 0