#!/bin/sh
#* screensaverset
#+ chris.gerke@gmail.com
#+
#+ Description: Default Screensaver.
#+
#+ Version: 1.0
#+
#+ History:
#+     1.0: Script.
#+
#+ TODO:
#+     * Add error checking?

ME=$0
SCRIPT_DIR="$1/Contents/Resources"
TARGET_DIR="$3"

#+ // fix
if [ -z "${TARGET_DIR}" ] || [ "${TARGET_DIR}" = "/" ]; then
 TARGET_DIR=""
fi

#+ UUID
if [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` == "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c51-62 | awk {'print tolower()'}`
elif [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` != "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-62`
fi

#+ ByHost
sudo /bin/mkdir -p "${HOME}/Library/Preferences/ByHost"

#+ com.apple.screensaver.plist
sudo /usr/bin/defaults write "${HOME}/Library/Preferences/com.apple.screensaver" "askForPassword" -int "1"
sudo /usr/bin/defaults write "${HOME}/Library/Preferences/com.apple.screensaver" "askForPasswordDelay" -int "5"

#+ com.apple.screensaver.${UUID}.plist
sudo /usr/bin/defaults write "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}" "CleanExit" -string "YES"
sudo /usr/libexec/PlistBuddy -c 'Add :CleanExit string YES' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c 'Add :idleTime integer 900' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict dict' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:iLifeMediaGroupType integer 0' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:moduleName string Default" "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c "Add :moduleDict:path string ${TARGET_DIR}/Library/Screen Savers/Default.slideSaver" "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c 'Add :moduleDict:type integer 4' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist"
sudo /usr/libexec/PlistBuddy -c 'Add :DisplayType string Photos' "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.Default.${UUID}.plist"

#+ Lockfile
sudo /bin/rm -Rf "${HOME}/Library/Preferences/com.apple.screensaver.plist.lockfile"
sudo /bin/rm -Rf "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.${UUID}.plist.lockfile"
sudo /bin/rm -Rf "${HOME}/Library/Preferences/ByHost/com.apple.screensaver.Default.${UUID}.plist.lockfile"

exit 0